# Generated by Django 2.2.11 on 2020-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
