# Generated by Django 2.2.11 on 2020-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocontest', '0002_profile_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
